// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/logn-soft/logn-back/internal/ent/area"
	"github.com/logn-soft/logn-back/internal/ent/location"
	"github.com/logn-soft/logn-back/internal/ent/predicate"
	"github.com/logn-soft/logn-back/internal/ent/technology"
	"github.com/logn-soft/logn-back/internal/ent/technologylevel"
	"github.com/logn-soft/logn-back/internal/ent/vacancy"
)

// VacancyQuery is the builder for querying Vacancy entities.
type VacancyQuery struct {
	config
	ctx                  *QueryContext
	order                []OrderFunc
	inters               []Interceptor
	predicates           []predicate.Vacancy
	withTechnologies     *TechnologyQuery
	withLocations        *LocationQuery
	withAreas            *AreaQuery
	withTechnologyLevels *TechnologyLevelQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VacancyQuery builder.
func (vq *VacancyQuery) Where(ps ...predicate.Vacancy) *VacancyQuery {
	vq.predicates = append(vq.predicates, ps...)
	return vq
}

// Limit the number of records to be returned by this query.
func (vq *VacancyQuery) Limit(limit int) *VacancyQuery {
	vq.ctx.Limit = &limit
	return vq
}

// Offset to start from.
func (vq *VacancyQuery) Offset(offset int) *VacancyQuery {
	vq.ctx.Offset = &offset
	return vq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vq *VacancyQuery) Unique(unique bool) *VacancyQuery {
	vq.ctx.Unique = &unique
	return vq
}

// Order specifies how the records should be ordered.
func (vq *VacancyQuery) Order(o ...OrderFunc) *VacancyQuery {
	vq.order = append(vq.order, o...)
	return vq
}

// QueryTechnologies chains the current query on the "technologies" edge.
func (vq *VacancyQuery) QueryTechnologies() *TechnologyQuery {
	query := (&TechnologyClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vacancy.Table, vacancy.FieldID, selector),
			sqlgraph.To(technology.Table, technology.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, vacancy.TechnologiesTable, vacancy.TechnologiesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocations chains the current query on the "locations" edge.
func (vq *VacancyQuery) QueryLocations() *LocationQuery {
	query := (&LocationClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vacancy.Table, vacancy.FieldID, selector),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, vacancy.LocationsTable, vacancy.LocationsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAreas chains the current query on the "areas" edge.
func (vq *VacancyQuery) QueryAreas() *AreaQuery {
	query := (&AreaClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vacancy.Table, vacancy.FieldID, selector),
			sqlgraph.To(area.Table, area.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, vacancy.AreasTable, vacancy.AreasPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTechnologyLevels chains the current query on the "technology_levels" edge.
func (vq *VacancyQuery) QueryTechnologyLevels() *TechnologyLevelQuery {
	query := (&TechnologyLevelClient{config: vq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vacancy.Table, vacancy.FieldID, selector),
			sqlgraph.To(technologylevel.Table, technologylevel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, vacancy.TechnologyLevelsTable, vacancy.TechnologyLevelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(vq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Vacancy entity from the query.
// Returns a *NotFoundError when no Vacancy was found.
func (vq *VacancyQuery) First(ctx context.Context) (*Vacancy, error) {
	nodes, err := vq.Limit(1).All(setContextOp(ctx, vq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{vacancy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vq *VacancyQuery) FirstX(ctx context.Context) *Vacancy {
	node, err := vq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Vacancy ID from the query.
// Returns a *NotFoundError when no Vacancy ID was found.
func (vq *VacancyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vq.Limit(1).IDs(setContextOp(ctx, vq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{vacancy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vq *VacancyQuery) FirstIDX(ctx context.Context) int {
	id, err := vq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Vacancy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Vacancy entity is found.
// Returns a *NotFoundError when no Vacancy entities are found.
func (vq *VacancyQuery) Only(ctx context.Context) (*Vacancy, error) {
	nodes, err := vq.Limit(2).All(setContextOp(ctx, vq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{vacancy.Label}
	default:
		return nil, &NotSingularError{vacancy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vq *VacancyQuery) OnlyX(ctx context.Context) *Vacancy {
	node, err := vq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Vacancy ID in the query.
// Returns a *NotSingularError when more than one Vacancy ID is found.
// Returns a *NotFoundError when no entities are found.
func (vq *VacancyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vq.Limit(2).IDs(setContextOp(ctx, vq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{vacancy.Label}
	default:
		err = &NotSingularError{vacancy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vq *VacancyQuery) OnlyIDX(ctx context.Context) int {
	id, err := vq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Vacancies.
func (vq *VacancyQuery) All(ctx context.Context) ([]*Vacancy, error) {
	ctx = setContextOp(ctx, vq.ctx, "All")
	if err := vq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Vacancy, *VacancyQuery]()
	return withInterceptors[[]*Vacancy](ctx, vq, qr, vq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vq *VacancyQuery) AllX(ctx context.Context) []*Vacancy {
	nodes, err := vq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Vacancy IDs.
func (vq *VacancyQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, vq.ctx, "IDs")
	if err := vq.Select(vacancy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vq *VacancyQuery) IDsX(ctx context.Context) []int {
	ids, err := vq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vq *VacancyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vq.ctx, "Count")
	if err := vq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vq, querierCount[*VacancyQuery](), vq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vq *VacancyQuery) CountX(ctx context.Context) int {
	count, err := vq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vq *VacancyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vq.ctx, "Exist")
	switch _, err := vq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vq *VacancyQuery) ExistX(ctx context.Context) bool {
	exist, err := vq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VacancyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vq *VacancyQuery) Clone() *VacancyQuery {
	if vq == nil {
		return nil
	}
	return &VacancyQuery{
		config:               vq.config,
		ctx:                  vq.ctx.Clone(),
		order:                append([]OrderFunc{}, vq.order...),
		inters:               append([]Interceptor{}, vq.inters...),
		predicates:           append([]predicate.Vacancy{}, vq.predicates...),
		withTechnologies:     vq.withTechnologies.Clone(),
		withLocations:        vq.withLocations.Clone(),
		withAreas:            vq.withAreas.Clone(),
		withTechnologyLevels: vq.withTechnologyLevels.Clone(),
		// clone intermediate query.
		sql:  vq.sql.Clone(),
		path: vq.path,
	}
}

// WithTechnologies tells the query-builder to eager-load the nodes that are connected to
// the "technologies" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VacancyQuery) WithTechnologies(opts ...func(*TechnologyQuery)) *VacancyQuery {
	query := (&TechnologyClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withTechnologies = query
	return vq
}

// WithLocations tells the query-builder to eager-load the nodes that are connected to
// the "locations" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VacancyQuery) WithLocations(opts ...func(*LocationQuery)) *VacancyQuery {
	query := (&LocationClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withLocations = query
	return vq
}

// WithAreas tells the query-builder to eager-load the nodes that are connected to
// the "areas" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VacancyQuery) WithAreas(opts ...func(*AreaQuery)) *VacancyQuery {
	query := (&AreaClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withAreas = query
	return vq
}

// WithTechnologyLevels tells the query-builder to eager-load the nodes that are connected to
// the "technology_levels" edge. The optional arguments are used to configure the query builder of the edge.
func (vq *VacancyQuery) WithTechnologyLevels(opts ...func(*TechnologyLevelQuery)) *VacancyQuery {
	query := (&TechnologyLevelClient{config: vq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vq.withTechnologyLevels = query
	return vq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Vacancy.Query().
//		GroupBy(vacancy.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vq *VacancyQuery) GroupBy(field string, fields ...string) *VacancyGroupBy {
	vq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VacancyGroupBy{build: vq}
	grbuild.flds = &vq.ctx.Fields
	grbuild.label = vacancy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Vacancy.Query().
//		Select(vacancy.FieldName).
//		Scan(ctx, &v)
func (vq *VacancyQuery) Select(fields ...string) *VacancySelect {
	vq.ctx.Fields = append(vq.ctx.Fields, fields...)
	sbuild := &VacancySelect{VacancyQuery: vq}
	sbuild.label = vacancy.Label
	sbuild.flds, sbuild.scan = &vq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VacancySelect configured with the given aggregations.
func (vq *VacancyQuery) Aggregate(fns ...AggregateFunc) *VacancySelect {
	return vq.Select().Aggregate(fns...)
}

func (vq *VacancyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vq); err != nil {
				return err
			}
		}
	}
	for _, f := range vq.ctx.Fields {
		if !vacancy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vq.path != nil {
		prev, err := vq.path(ctx)
		if err != nil {
			return err
		}
		vq.sql = prev
	}
	return nil
}

func (vq *VacancyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Vacancy, error) {
	var (
		nodes       = []*Vacancy{}
		_spec       = vq.querySpec()
		loadedTypes = [4]bool{
			vq.withTechnologies != nil,
			vq.withLocations != nil,
			vq.withAreas != nil,
			vq.withTechnologyLevels != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Vacancy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Vacancy{config: vq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vq.withTechnologies; query != nil {
		if err := vq.loadTechnologies(ctx, query, nodes,
			func(n *Vacancy) { n.Edges.Technologies = []*Technology{} },
			func(n *Vacancy, e *Technology) { n.Edges.Technologies = append(n.Edges.Technologies, e) }); err != nil {
			return nil, err
		}
	}
	if query := vq.withLocations; query != nil {
		if err := vq.loadLocations(ctx, query, nodes,
			func(n *Vacancy) { n.Edges.Locations = []*Location{} },
			func(n *Vacancy, e *Location) { n.Edges.Locations = append(n.Edges.Locations, e) }); err != nil {
			return nil, err
		}
	}
	if query := vq.withAreas; query != nil {
		if err := vq.loadAreas(ctx, query, nodes,
			func(n *Vacancy) { n.Edges.Areas = []*Area{} },
			func(n *Vacancy, e *Area) { n.Edges.Areas = append(n.Edges.Areas, e) }); err != nil {
			return nil, err
		}
	}
	if query := vq.withTechnologyLevels; query != nil {
		if err := vq.loadTechnologyLevels(ctx, query, nodes,
			func(n *Vacancy) { n.Edges.TechnologyLevels = []*TechnologyLevel{} },
			func(n *Vacancy, e *TechnologyLevel) { n.Edges.TechnologyLevels = append(n.Edges.TechnologyLevels, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vq *VacancyQuery) loadTechnologies(ctx context.Context, query *TechnologyQuery, nodes []*Vacancy, init func(*Vacancy), assign func(*Vacancy, *Technology)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Vacancy)
	nids := make(map[int]map[*Vacancy]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(vacancy.TechnologiesTable)
		s.Join(joinT).On(s.C(technology.FieldID), joinT.C(vacancy.TechnologiesPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(vacancy.TechnologiesPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(vacancy.TechnologiesPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Vacancy]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Technology](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "technologies" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (vq *VacancyQuery) loadLocations(ctx context.Context, query *LocationQuery, nodes []*Vacancy, init func(*Vacancy), assign func(*Vacancy, *Location)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Vacancy)
	nids := make(map[int]map[*Vacancy]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(vacancy.LocationsTable)
		s.Join(joinT).On(s.C(location.FieldID), joinT.C(vacancy.LocationsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(vacancy.LocationsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(vacancy.LocationsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Vacancy]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Location](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "locations" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (vq *VacancyQuery) loadAreas(ctx context.Context, query *AreaQuery, nodes []*Vacancy, init func(*Vacancy), assign func(*Vacancy, *Area)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Vacancy)
	nids := make(map[int]map[*Vacancy]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(vacancy.AreasTable)
		s.Join(joinT).On(s.C(area.FieldID), joinT.C(vacancy.AreasPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(vacancy.AreasPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(vacancy.AreasPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Vacancy]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Area](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "areas" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (vq *VacancyQuery) loadTechnologyLevels(ctx context.Context, query *TechnologyLevelQuery, nodes []*Vacancy, init func(*Vacancy), assign func(*Vacancy, *TechnologyLevel)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Vacancy)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.TechnologyLevel(func(s *sql.Selector) {
		s.Where(sql.InValues(vacancy.TechnologyLevelsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VacancyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "vacancy_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (vq *VacancyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vq.querySpec()
	_spec.Node.Columns = vq.ctx.Fields
	if len(vq.ctx.Fields) > 0 {
		_spec.Unique = vq.ctx.Unique != nil && *vq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vq.driver, _spec)
}

func (vq *VacancyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   vacancy.Table,
			Columns: vacancy.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: vacancy.FieldID,
			},
		},
		From:   vq.sql,
		Unique: true,
	}
	if unique := vq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := vq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vacancy.FieldID)
		for i := range fields {
			if fields[i] != vacancy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vq *VacancyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vq.driver.Dialect())
	t1 := builder.Table(vacancy.Table)
	columns := vq.ctx.Fields
	if len(columns) == 0 {
		columns = vacancy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vq.sql != nil {
		selector = vq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vq.ctx.Unique != nil && *vq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vq.predicates {
		p(selector)
	}
	for _, p := range vq.order {
		p(selector)
	}
	if offset := vq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VacancyGroupBy is the group-by builder for Vacancy entities.
type VacancyGroupBy struct {
	selector
	build *VacancyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vgb *VacancyGroupBy) Aggregate(fns ...AggregateFunc) *VacancyGroupBy {
	vgb.fns = append(vgb.fns, fns...)
	return vgb
}

// Scan applies the selector query and scans the result into the given value.
func (vgb *VacancyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vgb.build.ctx, "GroupBy")
	if err := vgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VacancyQuery, *VacancyGroupBy](ctx, vgb.build, vgb, vgb.build.inters, v)
}

func (vgb *VacancyGroupBy) sqlScan(ctx context.Context, root *VacancyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vgb.fns))
	for _, fn := range vgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vgb.flds)+len(vgb.fns))
		for _, f := range *vgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VacancySelect is the builder for selecting fields of Vacancy entities.
type VacancySelect struct {
	*VacancyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vs *VacancySelect) Aggregate(fns ...AggregateFunc) *VacancySelect {
	vs.fns = append(vs.fns, fns...)
	return vs
}

// Scan applies the selector query and scans the result into the given value.
func (vs *VacancySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vs.ctx, "Select")
	if err := vs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VacancyQuery, *VacancySelect](ctx, vs.VacancyQuery, vs, vs.inters, v)
}

func (vs *VacancySelect) sqlScan(ctx context.Context, root *VacancyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vs.fns))
	for _, fn := range vs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
